namespace MaterialDesignThemes.Wpf
{
    /// <summary>
    /// List of available icons for use with <see cref="Icon"/>.
    /// </summary>
    /// <remarks>
    /// All icons sourced from Material Design Icons Font - <see href="https://materialdesignicons.com/"/> - in accordance of 
    /// <see href="https://github.com/Templarian/MaterialDesign/blob/master/license.txt"/>.
    /// </remarks>
    public enum IconType
    {
        AutoGeneratedDoNotAmend
    }
}